# Generated by Django 5.0.6 on 2024-07-05 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_alter_movimiento_precio_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimiento',
            name='precio_total',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
