# Generated by Django 5.0.6 on 2024-08-23 19:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_alter_pagomovimiento_metodo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimiento',
            name='pago',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='inventario.pagomovimiento'),
        ),
    ]
