# Generated by Django 5.0.6 on 2024-07-06 03:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_alter_movimiento_precio_total'),
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallemovimiento',
            name='sucursal_producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.sucursalproducto'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='detallemovimiento',
            unique_together={('movimiento', 'sucursal_producto')},
        ),
        migrations.RemoveField(
            model_name='detallemovimiento',
            name='id_producto',
        ),
        migrations.RemoveField(
            model_name='detallemovimiento',
            name='id_sucursal',
        ),
    ]
