# Generated by Django 5.0.6 on 2024-08-23 19:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_alter_movimiento_pago'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimiento',
            name='pago',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventario.pagomovimiento'),
        ),
    ]
