# Generated by Django 5.0.6 on 2024-07-20 05:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=225)),
            ],
        ),
        migrations.CreateModel(
            name='Comuna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Giro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TipoAuxiliar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Auxiliar',
            fields=[
                ('rut_auxiliar', models.IntegerField(primary_key=True, serialize=False)),
                ('dv', models.IntegerField()),
                ('razon_social', models.CharField(blank=True, max_length=50)),
                ('direccion', models.CharField(max_length=50)),
                ('sitio_web', models.URLField(blank=True, max_length=50)),
                ('fecha_inicio_acuerdo', models.DateField()),
                ('telefono', models.CharField(blank=True, max_length=12)),
                ('activo', models.BooleanField()),
                ('comuna', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auxiliares.comuna')),
                ('tipo_auxiliar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auxiliares.tipoauxiliar')),
            ],
        ),
        migrations.CreateModel(
            name='ContactoAuxiliar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dv', models.IntegerField()),
                ('nombres', models.CharField(max_length=50)),
                ('apellidos', models.CharField(max_length=50)),
                ('correo', models.EmailField(blank=True, max_length=50)),
                ('telefono', models.IntegerField()),
                ('cargo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auxiliares.cargo')),
                ('rut_auxiliar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auxiliares.auxiliar')),
                ('tipo_auxiliar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auxiliares.tipoauxiliar')),
            ],
        ),
        migrations.CreateModel(
            name='AuxiliarGiro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut_auxiliar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auxiliares.auxiliar')),
                ('giro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auxiliares.giro')),
            ],
            options={
                'unique_together': {('rut_auxiliar', 'giro')},
            },
        ),
    ]
