# Generated by Django 5.0.6 on 2024-09-02 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auxiliares', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auxiliar',
            name='dv',
            field=models.CharField(max_length=1),
        ),
    ]
