# Generated by Django 5.0.6 on 2024-07-16 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auxiliares', '0002_alter_auxiliar_dv_alter_contactoauxiliar_dv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auxiliar',
            name='telefono',
            field=models.CharField(blank=True, max_length=12),
        ),
    ]
