# Generated by Django 5.0.6 on 2024-07-19 09:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auxiliares', '0003_alter_auxiliar_telefono'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auxiliar',
            name='comuna',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='auxiliares.comuna'),
        ),
    ]
