# Generated by Django 5.0.6 on 2024-07-19 09:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auxiliares', '0004_alter_auxiliar_comuna'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auxiliar',
            name='tipo_auxiliar',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='auxiliares.tipoauxiliar'),
        ),
    ]
