# Generated by Django 5.0.6 on 2024-07-19 09:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auxiliares', '0005_alter_auxiliar_tipo_auxiliar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auxiliar',
            name='tipo_auxiliar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auxiliares.tipoauxiliar'),
        ),
    ]
