# Generated by Django 5.0.6 on 2024-07-19 10:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auxiliares', '0006_alter_auxiliar_tipo_auxiliar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auxiliar',
            name='comuna',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auxiliares.comuna'),
        ),
    ]
