# Generated by Django 5.0.6 on 2024-07-06 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0005_sucursalproducto_and_more'),
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SucursalProducto',
        ),
    ]
